name: myenv
channels:
  - conda-forge
dependencies:
  - embree
  - tbb-devel
  - cython
  - numpy
  - setuptools
  - scipy
  - tqdm
  - geographiclib
  - requests
  - xarray
  - netcdf4
  - matplotlib
  - pillow
  - skyfield
  - pyproj
  - scikit-image
  - xdem
  - geopandas < 0.14